### ISSUE TITLE
Problems during setup

### ISSUE THREAD

**Issue by JanOwiesniak** [gaetanozappi/react-native-intent-exoplayer#1]
I had issues to integrate this library into my react native project and i want to share these insights with you to save you some headache :)

These are the things i had to do to get it working without any menu or video title (have not figured out why some variables are always nil)

# Fix compile errors

Add `implementation 'com.android.support.constraint:constraint-layout:1.1.0'` to **android/build.gradle** _dependencies_ and `http://dl.bintray.com/lukaville/maven` to _repositories_

```
dependencies {
  implementation 'com.android.support.constraint:constraint-layout:1.1.0'
}
```

```
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/lukaville/maven"
        }
    }
}
```

Add `tools:replace="android:allowBackup"` to **AndroidManifest.xml**

```
<manifest>
    <application tools:replace="android:allowBackup">
    </application>
</manifest>
```

Remove `@Override` from **VideoPlayerPackage.java**

```
public class VideoPlayerPackage implements ReactPackage {

    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Arrays.<NativeModule>asList(new VideoPlayerModule(reactContext));
    }

    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}
```

# Fix runtime errors

Comment out all occurances of `video_title` in **SimpleVideoStream.java** because `video_title` is always nil.

```
video_title = (TextView) findViewById(R.id.video_title);
```

Comment out `option.setOnClickListener` in **SimpleVideoStream.java** because `option` is always nil.

```
final ImageView option = (ImageView) findViewById(R.id.exo_option);
```

**Comment by gaetanozappi** [comment]
Hi, @JanOwiesniak  thank you for trying the module I created.
I have tried to minimize dependencies.
When I was developing it, installed it in a new project, I made some strange tests that these problems you listed did not happen to me.

What problems did the compiler give you exactly?

I don't think I have a class called: `VideoPlayerPackage`

If the title field is empty it should by default work like this: `title = b.getString ("title", "");`


Can I ask you to be more specific about the configuration you set?

Can you post a screeshot?

P.s.

Does the player work at the end, does it play the video correctly or not?

**Comment by JanOwiesniak** [comment]
Sorry for not responding to your questions. I'm not using this library anymore and ended up using a combination of:

- https://github.com/react-native-community/react-native-video
- https://github.com/itsnubix/react-native-video-controls
- https://github.com/cornedor/react-native-video-player
