### ISSUE TITLE
Portrait Videos are running in Landscape Mode

### ISSUE THREAD

**Issue by JanOwiesniak** [gaetanozappi/react-native-intent-exoplayer#2]

**Comment by gaetanozappi** [comment]
Hi @JanOwiesniak , Can I ask you to be more specific in your question?
Are you asking me to modify the `AndroidManifest `file the `android: screenOrientation `property and add the Portrait mode?

P.s.

If you want to do pull requests are welcome. ;)

**Comment by JanOwiesniak** [comment]
Sorry for not responding to your questions. I'm not using this library anymore and ended up using a combination of:

- https://github.com/react-native-community/react-native-video
- https://github.com/itsnubix/react-native-video-controls
- https://github.com/cornedor/react-native-video-player
